language: node_js
node_js:
  - "node"
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: f2d601a2-5fc2-4a6e-b00d-800e3fa6d606
  app: the-emotional-rhymer
  skip_cleanup: true